---

- name: Install docker
  import_role:
    name: angstwad.docker_ubuntu
  vars:
    # angstwad.docker_ubuntu logic depends on "python3" in the interpreter name
    ansible_python_interpreter: /usr/bin/python3
    # Default ha.pool.sks-keyservers.net fails DNS resolution
    apt_key_url: "hkp://keyserver.ubuntu.com:80"
    # Don't start by default; instead, the rootless user-daemon will start
    start_docker_daemon: false
    # We configure this elsewhere
    ufw_set_forward_policy: false
  
- name: Install docker rootless extras
  apt:
    name: docker-ce-rootless-extras
    state: present

# https://rootlesscontaine.rs/getting-started/
- name: Rootless Containers - Start the systemd user session on boot
  command: loginctl enable-linger "{{ gala_linux_user }}"

- name: Rootless Containers - Install uidmap utilities
  apt:
    name: uidmap
    state: present

- name: (User) Create the systemd user-instance unit
  command: dockerd-rootless-setuptool.sh install
  become: false

- name: (User) Set docker context
  command: docker context use rootless
  become: false

