---

- name: Install docker
  import_role:
    name: angstwad.docker_ubuntu
  vars:
    # angstwad.docker_ubuntu logic depends on "python3" in the interpreter name
    ansible_python_interpreter: /usr/bin/python3
    # Default ha.pool.sks-keyservers.net fails DNS resolution
    apt_key_url: "hkp://keyserver.ubuntu.com:80"
    # Make sure to add the gala user here
    docker_group_members:
      - "{{ gala_linux_user }}"
    # We configure this elsewhere
    ufw_set_forward_policy: false
