---
# tasks file for rob-gala

- name: Basic Ubuntu patching
  include_tasks: ubuntu.yml

- name: Configure system firewall (UFW)
  include_tasks: firewall.yml

- name: Install and configure Minikube
  include_tasks: minikube.yml
