---
# tasks file for rob-gala

- name: Basic Ubuntu patching
  import_tasks: 01-ubuntu.yml

- name: Configure system firewall (UFW)
  import_tasks: 02-firewall.yml

- name: Configure Git
  import_tasks: 03-git.yml

- name: Install and configure Docker
  import_tasks: 04-docker.yml

- name: Set up the environment files
  import_tasks: 05-env.yml
  become: false

- name: Build and run the container image
  import_tasks: 06-container.yml
  become: false
